package com.myFirstBDD.daoTest.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.myFirstBDD.daoTest.domain.Employe;

public class EmployeDaoImpl implements EmployeDAO {

	Connection conn = null;
	Statement state = null;
	ResultSet rs = null;
	
	public EmployeDaoImpl(Connection connection) {
		this .conn = connection;
	}
	
	@Override
	public Employe insertEmploye(Employe employe) {
		try {
			String insertSQL = "insert into employe(login, nom, prenom, password) " + "values(?, ?, ?, ?)";
			PreparedStatement insertemp = conn.prepareStatement(insertSQL, Statement.RETURN_GENERATED_KEYS);
			insertemp.setString(1, employe.getLogin());
			insertemp.setString(2, employe.getNom());
			insertemp.setString(3, employe.getPrenom());
			insertemp.setString(4, employe.getPassword());
			
			insertemp.executeUpdate();
			
			ResultSet tableKeys = insertemp.getGeneratedKeys();
			tableKeys.next();
			int autoGeneratedID = tableKeys.getInt(1);
			System.out.println("Generated key for new employe : " + autoGeneratedID + "\n");
			employe.setId(autoGeneratedID);
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return employe;

	}

	@Override
	public void updateEmploye(Employe employe) {
		
		try {
			String sql = "update employe " + "set nom = ?, prenom = ? where id = ?";
			PreparedStatement ps = conn.prepareStatement(sql);
			ps.setInt(3, employe.getId());
			ps.setString(1, employe.getNom());
			ps.setString(2, employe.getPrenom());		
			
			ps.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

	@Override
	public void removeEmploye(int empID) {
		try {
			String sql = "delete from employe " + "where id = ?";
			PreparedStatement ps;
			ps = conn.prepareStatement(sql);
			ps.setInt(1, empID);
			ps.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	@Override
	public Employe getEmploye(int empID) {
		Employe employe = null;
		try {
			state = conn.createStatement();
			rs = state.executeQuery("SELECT * FROM employe where id = " + empID);
			
			while (rs.next()) {
				employe = new Employe();
				employe.setId(rs.getInt("id"));
				employe.setNom(rs.getString("nom"));
				employe.setPrenom(rs.getString("prenom"));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return employe;
	}

	@Override
	public Employe login(String login, String password) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<Employe> getAllEmploye() {
		List<Employe> employes = new ArrayList<>();
		Employe employe = null;
		try {
			state = conn.createStatement();
			rs = state.executeQuery("SELECT * FROM employe");
			
			while (rs.next()) {
				employe = new Employe();
				employe.setId(rs.getInt("id"));
				employe.setNom(rs.getString("nom"));
				employe.setPrenom(rs.getString("prenom"));
				employes.add(employe);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return employes;
	}

}
